Capstone/Pages/SubEvents/AddSubActivity.cshtml.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Capstone.Pages.DB;
using Capstone.Pages.Data_Classes;

namespace Capstone.Pages.Subevents
{
    public class AddSubActivityModel : PageModel
    {
        [BindProperty]
        public SubActivity SubActivity { get; set; }

        public List<SubEvent> SubEvents { get; set; }

        public void OnGet()
        {
            // Retrieve the list of SubEvents to populate a dropdown or any other UI element
            SubEvents = DBClass.GetSubEvents();
        }

        public IActionResult OnPost()
        {
            // Retrieve the selected SubEventID directly from the form
            int subEventID = int.Parse(Request.Form["SubEventID"]);

            // Set the SubEventID for the SubActivity
            SubActivity.SubEventID = subEventID;

            // Call your AddSubActivity method
            DBClass.AddSubActivity(SubActivity);

            return RedirectToPage("/Events/Index");
        }
    }
}

Capstone/Pages/SubEvents/Index.cshtml.cs
using Capstone.Pages.Data_Classes;
using Capstone.Pages.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace Capstone.Pages.Subevents
{
    public class AddSubEventModel : PageModel
    {
        [BindProperty]
        public SubEvent SubEvent { get; set; }
        [BindProperty]
        public Event Event { get; set; }
        public List<SelectListItem> EventList { get; set; }

        public void OnGet()
        {
            EventList = DBClass.GetAllEvents(); // Implement this to fetch all events
        }

        public IActionResult OnPost()
        {
            HttpContext.Session.SetInt32("SelectedEvent", Event.EventID);

            if (!ModelState.IsValid)
            {
                return Page();
            }

            return RedirectToPage("./NewSubEvent");
        }

        // Add a new action method to handle the View Attendance button click
        public IActionResult OnPostViewAttendance()
        {
            HttpContext.Session.SetInt32("SelectedEvent", Event.EventID);
            // Redirect to the EventAttendance page and pass the selected event ID
            return RedirectToPage("/Events/EventAttendance", new { eventId = Event.EventID });
        }
    }
}

Capstone/Pages/SubEvents/NewSubEvent.cshtml.cs
using Capstone.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Capstone.Pages.DB;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace Capstone.Pages.SubEvents
{
    public class NewSubEventModel : PageModel
    {
        [BindProperty]
        public SubEvent Subevent { get; set; }

        public List<User> Users { get; set; }

        public void OnGet()
        {
            Users = DBClass.GetUsers();
        }

        public IActionResult OnPost()
        {
            // Retrieve the selected HostID directly from the form
            //int hostID = int.Parse(Request.Form["HostID"]);

            //Subevent.HostID = hostID;

            int selectedEvent = (int)HttpContext.Session.GetInt32("SelectedEvent");
            Subevent.EventID = selectedEvent;

            // Retrieve the selected HostID directly from the form
            int hostID = Subevent.HostID;

            // Update the UserType of the selected host to "Host"
            DBClass.UpdateUserType(hostID, "Host");

            DBClass.AddSubEvent(Subevent);

            // Redirect to the AddSubActivity page in the same folder
            return RedirectToPage("/Events/Index");
        }


    }
}

Capstone/Pages/SubEvents/AddSubActivity.cshtml
@page
@model Capstone.Pages.Subevents.AddSubActivityModel
@{
}

<link href="~/css/site.css" rel="stylesheet" />

<section id="addSUBactivitypage">
    <h2>Enter Sub-Activity Information</h2>
    <form id="addactivityform" method="post" asp-action="SubActivity">
        <div class="form-group">
            <label for="Name">Name</label>
            <input class="stylefield" type="text" asp-for="SubActivity.Name" class="form-control" id="Name" name="Name" placeholder="Enter subactivity name">
        </div>

        <div class="form-group">
            <label for="Description">Description</label>
            <textarea class="stylefield" asp-for="SubActivity.Description" class="form-control" id="Description" name="Description" placeholder="Enter description"></textarea>
        </div>

        <div class="form-group">
            <label for="SubEventID">SubEvent</label>
            <select asp-for="SubActivity.SubEventID" class="form-control" id="SubEventID" name="SubEventID">
                <option value="">Select SubEvent</option>
                @if (Model.SubEvents != null)
                {
                    foreach (var subEvent in Model.SubEvents)
                    {
                        <option value="@subEvent.SubEventID">@subEvent.Name</option>
                    }
                }
            </select>
        </div>

        <button class="btnstyle" type="submit" class="btn btn-primary">Submit</button>
        
    </form>

    

Capstone/Pages/SubEvents/Index.cshtml
@page
@model Capstone.Pages.Subevents.AddSubEventModel
@{
}

<link href="~/css/site.css" rel="stylesheet" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet">

<section id="subeventindex">
    <h2>Manage Subevents</h2>
    <form method="post">
        <label for="event">Select Event:</label>
        <select class="stylefield" asp-for="Event.EventID" asp-items="Model.EventList">
            <option value="">-- Select an Event --</option>
        </select>

        <button class="btnstyle" type="submit" class="btn btn-danger">Create SubEvents</button>

        <!-- Add a View Attendance button -->
        <button class="btnstyle" type="submit" name="ViewAttendance" asp-page-handler="ViewAttendance" class="btn btn-primary">View Attendance</button>
    </form>
</section>

Capstone/Pages/SubEvents/NewSubEvent.cshtml
@page
@model Capstone.Pages.SubEvents.NewSubEventModel;
@{
}

<link href="~/css/site.css" rel="stylesheet" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet">

<section id="addSUBeventpage">
    <h2>Enter Sub-Event Information</h2>
    <form id="addeventform" method="post" asp-page="NewSubEvent">
        <div class="form-group">
            <label>Name</label>
            <input class="stylefield" type="text" asp-for="Subevent.Name" class="form-control" placeholder="Enter subevent name">
        </div>

        <div class="form-group">
            <label for="Description">Description</label>
            <textarea class="stylefield" asp-for="Subevent.Description" class="form-control"  placeholder="Enter description"></textarea>
        </div>

        <div class="form-group">
            <label for="SubEventType">SubEvent Type</label>
            <input class="stylefield" asp-for="Subevent.SubEventType" type="text" class="form-control"  placeholder="Enter sub event type">
        </div>

        <div class="form-group">
            <label for="EstimatedAttendance">Estimated Attendance</label>
            <input class="stylefield" asp-for="Subevent.EstimatedAttendance" type="number" class="form-control"  placeholder="Enter estimated attendance">
        </div>

        <div class="form-group">
            <label for="HostID">Host</label>
            <select asp-for="Subevent.HostID" class="form-control">
                <option value="">Select Host</option>
                @if (Model.Users != null)
                {
                    foreach (var user in Model.Users)
                    {
                        <option value="@user.UserID">@($"{user.FirstName} {user.LastName}")</option>
                    }
                }
            </select>
        </div>




        <button class="btnstyle" type="submit" class="btn btn-primary">Submit</button>
        <button class="btnstyle" type="button" class="btn btn-secondary" onclick="populateForm()">Populate</button>



    </form>


    <script>
        function populateForm() {
            document.getElementById("Name").value = "Python Workshop";
            document.getElementById("Description").value = "Come enhance your Python Skills!";
            document.getElementById("SubEventType").value = "Workshop";
            document.getElementById("EstimatedAttendance").value = 50;

            // Assuming "Ted Lasso" is a valid entry in your dropdown list
            document.getElementById("HostID").value = "Ted Lasso";
        }
    </script>
</section>