Capstone/Pages/Events/AddEvent.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using Capstone.Pages.DB;
using Capstone.Pages.Data_Classes;
using System;

namespace Capstone.Pages.Events
{
    public class AddEventModel : PageModel
    {

        public int organizerID;

        [BindProperty]
        public Event NewEvent { get; set; }

        public IActionResult OnGet()
        {
            organizerID = HttpContext.Session.GetInt32("userID").Value;
            ViewData["OrganizerID"] = organizerID;
            NewEvent = new Event();
            return Page();
        }

        public IActionResult OnPost()
        {
            
            

            // Assign the OrganizerID to the OrganizerID property of the new event
            NewEvent.OrganizerID = HttpContext.Session.GetInt32("userID").Value;

            // Get UserType directly from the database
            string username = HttpContext.Session.GetString("username");
            string userType = DBClass.GetUserTypeByName(username);

            

            // Redirect based on UserType
            if (userType.Trim().Equals("Admin", StringComparison.OrdinalIgnoreCase))
            {
                // Insert requested event
                DBClass.InsertRequestedEvent(NewEvent);

                // Redirect to EventApproval page for Admin
                return RedirectToPage("./Index");
            }
            else
            {
                // Insert requested event
                DBClass.InsertRequestedEvent(NewEvent);

                // Redirect to the current page for non-Admin users
                return RedirectToPage("/Events/Index");
            }
        }


    }
}

Capstone/Pages/Events/EventApproval.cshtml.cs
using Capstone.Pages.Data_Classes;
using Capstone.Pages.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace Capstone.Pages.Events
{
    public class EventApprovalModel : PageModel
    {
        //public List<Event> RequestedEvents { get; set; }

        public Event AddEvent { get; set; }

        public class EventWithUserInfo : Event
        {
            public string OrganizerName { get; set; }
        }

        public List<EventWithUserInfo> RequestedEvents { get; set; }

        public void OnGet()
        {
            RequestedEvents = new List<EventWithUserInfo>();
            SqlDataReader getEvents = DBClass.GetRequestedEvents();

            while (getEvents.Read())
            {
                int organizerID = Convert.IsDBNull(getEvents["OrganizerID"]) ? 0 : (int)getEvents["OrganizerID"];

                // Skip the current iteration if OrganizerID is null
                if (organizerID == 0)
                {
                    continue;
                }

                // Fetch user information based on OrganizerID
                User organizer = DBClass.GetUserById(organizerID);

                RequestedEvents.Add(new EventWithUserInfo
                {
                    Name = getEvents["Name"].ToString(),
                    Address = getEvents["Address"].ToString(),
                    StartDate = getEvents["StartDate"].ToString(),
                    EndDate = getEvents["EndDate"].ToString(),
                    EventType = getEvents["EventType"].ToString(),
                    Description = getEvents["Description"].ToString(),
                    OrganizerID = organizerID,
                    RegistrationCost = (int)Convert.ToDecimal(getEvents["RegistrationCost"]),
                    EstimatedAttendance = (int)Convert.ToDecimal(getEvents["EstimatedAttendance"]),
                    OrganizerName = $"{organizer.FirstName} {organizer.LastName}", // Include OrganizerName
                });
            }

            DBClass.CapDBConn.Close();
        }


        public IActionResult OnPostApprove(string EventName)
        {
            Event approvedEvent = DBClass.GetRequestedEventDetails(EventName);
            if (approvedEvent != null)
            {
                DBClass.InsertEvent(approvedEvent);

                // Update UserType of the associated organizer to "Organizer"
                int organizerID = approvedEvent.OrganizerID;
                DBClass.UpdateUserType(organizerID, "Organizer");

                return RedirectToPage("/SubEvents/Index");
            }

            return RedirectToPage("/Events/");
        }


        public IActionResult OnPostDeny()
        {
            return RedirectToPage("/Menu");
        }


    }
}

Capstone/Pages/Events/EventAttendance.cshtml.cs
using Capstone.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using Capstone.Pages.DB;

namespace Capstone.Pages.Attendance
{
    public class EventAttendanceModel : PageModel
    {
        public List<EventRegistration> EventRegistrations { get; set; }
        public List<User> Users { get; set; }

        public void OnGet(int eventId)
        {
            // Retrieve the event registrations for the specified event
            EventRegistrations = DBClass.GetEventRegistrationsByEventId(eventId);

            // Retrieve the users for the event registrations
            Users = new List<User>();
            foreach (var registration in EventRegistrations)
            {
                var user = DBClass.GetUserById(registration.UserID);
                Users.Add(user);
            }
        }
    }
}

Capstone/Pages/Events/EventDisplay.cshtml.cs
using System.Collections.Generic;
using Capstone.Pages.Data_Classes; 

namespace Capstone.Pages.Events
{
    public class EventDisplayModel
    {
        public List<Event> Events { get; set; }
    }
}

Capstone/Pages/Events/EventSignUp.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Capstone.Pages.DB;

namespace Capstone.Pages.Events
{
    public class EventSignUpModel : PageModel
    {
        public EventDisplayModel EventModel { get; set; }



        public IActionResult OnGet()
        {
            // Retrieve events from the database
            EventModel = new EventDisplayModel
            {
                Events = DBClass.GetEventsList() 
            };
      

            return Page();
        }

        public IActionResult OnPostSignUp(int eventId)
        {
            // Get UserID from session state
            int? userId = HttpContext.Session.GetInt32("userID").Value;

            if (userId.HasValue)
            {
                // Add user to the EventRegistration table
                DBClass.AddEventRegistration(userId.Value, eventId);

                ViewData["SignUpMessage"] = "Event sign-up successful!";
            }
            else
            {
                ViewData["SignUpMessage"] = "User not logged in.";
            }

            // Refresh the page to reflect the updated sign-up status
            return RedirectToPage("/Menu");
        }

    }
}

Capstone/Pages/Events/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Capstone.Pages.Events
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
           
        }

        //public IActionResult OnPostAddEvent()
        //{
        //    return RedirectToPage("AddEvent");
        //}
    }
}

Capstone/Pages/Events/SendEmail.cshtml.cs
using Capstone.Pages.Data_Classes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Mail;

namespace Capstone.Pages.Events
{
    public class SendEmailModel : PageModel
    {
        [BindProperty]
        public EmailModel EmailForm { get; set; }

        public void OnGet()
        {
            EmailForm = new EmailModel();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                EmailSender.SendEmail(EmailForm);
                ViewData["Message"] = "Email sent successfully.";
            }

            return Page();
        }
    }
}

Capstone/Pages/Events/AddEvent.cshtml
@page
@model Capstone.Pages.Events.AddEventModel
@{
}


<link href="~/css/site.css" rel="stylesheet" />


<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,400&display=swap" rel="stylesheet">


<section id="addeventpage">
    <form>
        <h2>Enter Event Information and Request Approval</h2>

    </form>


    <form id="addeventform" asp-page="AddEvent">
        <input class="stylefield" type="text" asp-for="NewEvent.Name" placeholder="Event Name" /><br>
        <input class="stylefield" type="text" asp-for="NewEvent.Address" placeholder="Address" /><br>
        <input class="stylefield" type="text" asp-for="NewEvent.RegistrationCost" placeholder="Registration Cost" /><br>
        <input class="stylefield" type="text" asp-for="NewEvent.EstimatedAttendance" placeholder="Estimated Attendance" /><br>
        <input class="stylefield" type="text" asp-for="NewEvent.StartDate" placeholder="Start Date" /><br>
        <input class="stylefield" type="text" asp-for="NewEvent.EndDate" placeholder="End Date" /><br>
        <input class="stylefield" type="text" asp-for="NewEvent.EventType" placeholder="Event Type" /><br>
        <input class="stylefield" type="text" asp-for="NewEvent.Description" placeholder="Description" /><br>
        <button class="btnstyle" type="submit">Request Approval</button>
        <button class="btnstyle" type="button" onclick="populateForm()">Populate</button>
    </form>

    <script>
        function populateForm() {

            var predefinedValues = {
                Name: "Sample Event",
                Address: "123 Main Street",
                RegistrationCost: "50",
                EstimatedAttendance: "100",
                StartDate: "2023-01-01",
                EndDate: "2023-01-03",
                EventType: "Conference",
                Description: "This is a sample event."
            };


            Object.keys(predefinedValues).forEach(function (key) {
                var inputField = document.querySelector('[name="NewEvent.' + key + '"]');
                if (inputField) {
                    inputField.value = predefinedValues[key];
                }
            });
        }
    </script>
</section>

Capstone/Pages/Events/EventApproval.cshtml
@page
@model Capstone.Pages.Events.EventApprovalModel
@{
    ViewData["Title"] = "Event Approval";
}


<h2>Event Approval</h2>

@if (Model.RequestedEvents.Count > 0)
{
    <table>
        <thead>
            <tr>
                <th>Event Name</th>
                <th>Address</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Event Type</th> 
                <th>Description</th>
                <th>Registration Cost</th>
                <th>Estimated Attendance</th>
                <th>Organizer</th>

             

               
            </tr>
        </thead>
        <tbody>
            @foreach (var requestedEvent in Model.RequestedEvents)
            {
                <tr>
                    <td>@requestedEvent.Name</td>
                    <td>@requestedEvent.Address</td>
                    <td>@requestedEvent.StartDate</td>
                    <td>@requestedEvent.EndDate</td>
                    <td>@requestedEvent.EventType</td>
                    <td>@requestedEvent.Description</td>
                    <td>@requestedEvent.RegistrationCost</td>
                    <td>@requestedEvent.EstimatedAttendance</td>
                    <td>@requestedEvent.OrganizerName</td>
                    <td>
                        <form method="post" asp-page-handler="Approve" asp-route-EventName="@requestedEvent.Name">
                            <button type="submit" class="btn btn-success">Approve</button>
                        </form>
                        <form method="post" asp-page-handler="Deny" asp-route-EventID="@requestedEvent.EventID">
                            <button type="submit" class="btn btn-danger">Deny</button>
                        </form>
                    </td>

            
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No events requested.</p>
}

Capstone/Pages/Events/EventAttendance.cshtml
@page "{eventId:int}"
@model Capstone.Pages.Attendance.EventAttendanceModel
@{
    ViewData["Title"] = "Event Attendance";
}

<h2>Event Attendance</h2>

<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td>@user.FirstName</td>
                <td>@user.LastName</td>
                <td>@user.Email</td>
                <td>@user.PhoneNumber</td>
            </tr>
        }
    </tbody>
</table>

Capstone/Pages/Events/EventDisplay.cshtml
@page
@model Capstone.Pages.Events.EventDisplayModel
@{
}

Capstone/Pages/Events/EventSignUp.cshtml
@page
@model Capstone.Pages.Events.EventSignUpModel
@{
}

<h2>Event Sign-Up</h2>

<form method="post" asp-page-handler="SignUp">
    <div>
        @if (Model.EventModel != null && Model.EventModel.Events != null)
        {
            foreach (var eventItem in Model.EventModel.Events)
            {
                <div class="container">
                    <div class="row">
                        <div class="col-11 shadow p-3 mb-5 bg-body-tertiary rounded">

                            <h4>@eventItem.Name</h4>
                            <p>@eventItem.Description</p>
                            <p class="d-none">ID: @eventItem.EventID</p>
                            <!-- <div class="text-start"> -->
                            <button class="text-start" type="button" onclick="location.href='@Url.Page("EventSignUp", "SignUp", new { eventId = eventItem.EventID })'">Sign Up</button>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</form>

Capstone/Pages/Events/Index.cshtml
@page
@model Capstone.Pages.Events.IndexModel
@{
}


<form asp-page="Index">
    <button><a class="link" href="./AddEvent" class="btn btn-primary">Create Event</a></button>
    <button><a class="link" href="/AssignRooms/Index" class="btn btn-primary">Assign Rooms</a></button>
    <button><a class="link" href="/SubEvents/Index" class="btn btn-primary">Manage Sub-Events</a></button>
    <button><a class="link" href="/SubEvents/AddSubActivity" class="btn btn-primary">Add a Sub-Activity</a></button>

        </div>
        <div class="row">
            <div class="col-8 shadow p-3 mb-5 bg-body-tertiary rounded">
                <h3>Edit exisiting events</h3>
                <a class="link" href="/AssignRooms/Index" class="btn btn-primary">Assign Rooms</a>
                <a class="link" href="/SubEvents/Index" class="btn btn-primary">Manage Sub-Events</a>
                <a class="link" href="/SubEvents/AddSubActivity" class="btn btn-primary">Add a Sub-Activity</a>
            </div>
        </div>
    </form>
</div>

Capstone/Pages/Events/SendEmail.cshtml
@page
@model Capstone.Pages.Events.SendEmailModel
@{
    ViewData["Title"] = "Send Email";
}

<h1>@ViewData["Title"]</h1>

<form method="post">
    <label for="ToEmail">To Email:</label>
    <input type="text" asp-for="EmailForm.ToEmail" required />

    <label for="Subject">Subject:</label>
    <input type="text" asp-for="EmailForm.Subject" required />

    <label for="Body">Body:</label>
    <textarea asp-for="EmailForm.Body" required></textarea>

    <button type="submit">Send Email</button>
</form>

<p>@ViewData["Message"]</p>