Capstone/Pages/DBLogin.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using Capstone.Pages.DB;

namespace Capstone.Pages
{
    public class DBLoginModel : PageModel
    {
        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public IActionResult OnPost()
        {
            if (DBClass.HashedParameterLogin(Username, Password))
            {
                // Get UserID by username
                int userID = DBClass.GetUserIDByName(Username);

                string userType = DBClass.GetUserTypeByName(Username);
                ViewData["userType"] = userType;


                // Set UserID in session state
                HttpContext.Session.SetInt32("userID", userID);

                HttpContext.Session.SetString("username", Username);
                ViewData["LoginMessage"] = "Login Successful!";
                DBClass.CapDBConn.Close();
                return RedirectToPage("Menu");
            }
            else
            {
                ViewData["LoginMessage"] = "Username and/or Password Incorrect";
                DBClass.CapDBConn.Close(); 
                return Page();
            }
        }

        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return Page();
        }
    }
}

Capstone/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Capstone.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Capstone/Pages/Index.cshtml.cs
using Capstone.Pages.Data_Classes;
using Capstone.Pages.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Capstone.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public string SearchKeyword { get; set; }
        [BindProperty]
        //public List <Event> x { get; set; }
        public List<Event> Events { get; set; }
        [BindProperty]
        public string Description { get; set; }
        


        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToPage("/DBLogin");
            }
            else
            {
                return Page();
            }
        }


        //public void OnPostSearch()
        //{
         //   HttpContext.Session.SetString("SearchKeyword", SearchKeyword);

         //   Events = new List<Event>();

          //  var eventSearch = DBClass.SearchEvent(SearchKeyword);
         //   while (eventSearch.Read())
         //   {
           //     Events.Add(new Event
          //      {
          //          Description = eventSearch.GetString("Description"),
           //         MeetingRoom = eventSearch.GetString("MeetingRoom")

             //   });
           // }
           // DBClass.Lab2Connection.Close();
       // }

        //public void OnPostSearch()
        //{
        //    HttpContext.Session.SetString("SearchKeyword", SearchKeyword);
        //    var eventSearch = DBClass.SearchEvent(SearchKeyword);
        //    x = new List<Event>();
        //    while (eventSearch.Read())
        //    {
        //        x.Add(
        //            new Event(
        //                eventSearch["Description"].ToString(),
        //                eventSearch["MeetingRoom"].ToString()
        //                ));
        //    }
        //    DBClass.Lab2Connection.Close();
        //}

        //public IActionResult OnPost()
        //{

        //    //var eventSearch = DBClass.SearchEvent(SearchKeyword);
        //    //while (eventSearch.Read())
        //    //{
        //    //    x = eventSearch.GetString("Description");
        //    //}
        //    //return Page();


        //}

    }
}

Capstone/Pages/Menu.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using Capstone.Pages.DB;
using Capstone.Pages.Data_Classes;

namespace Capstone.Pages
{
    public class MenuModel : PageModel
    {
        public string HomePageUrl { get; } = "/Index";
        public string EventsPageUrl { get; } = "/Events";
        public string CalendarPageUrl { get; } = "/Calendar";
        public string MySchedulePageUrl { get; } = "/MySchedule";
        public string ProfilePageUrl { get; } = "/Profile";
        public string SettingsPageUrl { get; } = "/Settings";
        public string SendEmailPageUrl { get; } = "/Events/SendEmail";
        public string EventSignUpUrl { get; } = "/Events/EventSignUp";

        public int OrganizerID { get; private set; }

        public List<Event> UpcomingEvents { get; private set; }

        public IActionResult OnGet()
        {
            // Get the UserID from the session
            int organizerID = HttpContext.Session.GetInt32("userID").Value;
            OrganizerID = organizerID;

            ViewData["OrganizerID"] = organizerID;

            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToPage("/DBLogin");
            }
            else
            {
                // Retrieve upcoming events for the logged-in user
                UpcomingEvents = DBClass.GetEventsForAttendee(organizerID);

                return Page();
            }
        }

        public IActionResult OnPostLogoutHandler()
        {
            HttpContext.Session.Clear();
            return Page();
        }
    }
}

Capstone/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Capstone.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Capstone/Pages/Profile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Capstone.Pages
{
    public class ProfileModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Capstone/Pages/SignUp.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Capstone.Pages.DB;
using Capstone.Pages.Data_Classes;

namespace Capstone.Pages
{
    public class SignUpModel : PageModel
    {
        [BindProperty]
        public User NewUser { get; set; }

        [BindProperty]
        public string Password { get; set; }

        public IActionResult OnPost()
        {
            // Add user to the User table
            DBClass.AddEventUser(NewUser);

            // Hash the password and add username and hashed password to the HashedCredentials table
            
            DBClass.CreateHashedUser(NewUser.Username, Password);

            return RedirectToPage("/Index");
        }
    }
}

Capstone/Pages/DBLogin.cshtml
@page
@model Capstone.Pages.DBLoginModel
@{
    Layout = null;
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Capstone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    @*  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/Capstone.styles.css" asp-append-version="true" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">

    <style>
        .form-signin {
            max-width: 550px;
            padding: 1rem;
            padding-top: 200px;
        }

            .form-signin .form-floating:focus-within {
                z-index: 2;
            }

            .form-signin input[type="email"] {
                margin-bottom: -1px;
                border-bottom-right-radius: 0;
                border-bottom-left-radius: 0;
            }

            .form-signin input[type="password"] {
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }

        body, html {
            height: 100%;
            margin: 0;
            background-color: #F0F3F2;
            font-family: 'Public Sans', sans-serif;
        }

        main {
            background-color: #F0F3F2;
        }

        button {
            color: white;
            background-color: #648B7F;
            padding: .5em 2em;
            border: none;
            margin-top: 10px;
        }

    </style>




</head>
@{
    if (ViewData["LoginMessage"] != null)
    {
        <p class="text-success">@ViewData["LoginMessage"]</p>

    }
}

@{
    if (HttpContext.Session.GetString("username") != null)
    {
        <p>@HttpContext.Session.GetString("username") logged in</p>

        //log out
        <form asp-page="DBLogin" asp-page-handler="LogoutHandler">
            <input type="submit" class="btn btn-danger" value="logout">
        </form>
    }

    else if (HttpContext.Session.GetString("LoginError") != null)
    {
        <p class="text-danger">@HttpContext.Session.GetString("LoginError")</p>

        //try login again
        <form asp-page="DBLogin">
            <input asp-for="Username" class="form-control" placeholder="Enter Username" />
            <br />
            <input asp-for="Password" class="form-control" type="password" placeholder="Enter Password" />
            <br />
            <input type="submit" class="btn btn-primary" />

        </form>
    }

    else
    {
        //first time loading

        // <form asp-page="DBlogin">
        //     <input asp-for="Username" class="form-control" placeholder="Enter Username" />
        //     <br />
        //     <input asp-for="Password" class="form-control" type="password" placeholder="Enter Password" />
        //     <br />
        //     <input type="submit" value="Login" class="btn btn-primary" />
        //     <br />
        //     <br />
        // </form>
        // <a asp-page="/SignUp"> Haven't created an account? Register Here.</a>
        // <button type="button" class="btn btn-secondary" onclick="populateForm()">Populate</button>

        
            <form asp-page="DBLogin">
                <main class="form-signin w-100 m-auto">
               
                <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

                <div class="form-floating">
                    <input asp-for="Username" type="Username" class="form-control" id="floatingInput" placeholder="Username">
                    
                </div>
                <div class="form-floating">
                    <input asp-for="Password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                    
                </div>

                <div class="form-check text-start my-3">
                    <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
                    <label class="form-check-label" for="flexCheckDefault">
                        Remember me
                    </label>
                </div>
                <a asp-page="/SignUp"> Haven't created an account? Register Here.</a>
                <button type="submit">Login!</button>
                <button type="button" class="btn btn-secondary" onclick="populateForm()">Populate</button>
                </main>
            </form>
        



    }
}

<script>
    function populateForm() {
        // Set predefined values for the fields
        document.querySelector('input[name="Username"]').value = "TestUser";
        document.querySelector('input[name="Password"]').value = "password";
    }
</script>

Capstone/Pages/Index.cshtml
@page
@model Capstone.Pages.IndexModel
@{
}


@{
    if (HttpContext.Session.GetString("username") != null)
    {
        <p>@HttpContext.Session.GetString("username") logged in</p>

        //log out
        <form asp-page="DBLogin" asp-page-handler="LogoutHandler">
            <input type="submit" class="btn btn-danger" value="logout">
        </form>
    }
}

<div class="text-center">
    <h1>Welcome!</h1>
    <br />
    <br />
    <div>
        <a href="/ConferenceSignUp" class="btn btn-primary">Sign up for Events and Conferences</a>
    </div>
    <br />
    <br />
    <a href="/SummaryPage" class="btn btn-primary">Check out your Upcoming Events</a>
    <br />
    <br />
    <a href="/ShowUserInfo" class="btn btn-primary">Show all User Information</a>
    <br />
    <br />
    <p>Search for Events</p>
    <form asp-page="Index" method="post" class="d-flex" role="search">
        <input class="form-control me-2" asp-for="SearchKeyword" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>

</div>
@{
    if (Model.Events != null)
    {
        <h3>Events</h3>
        <table class="table table-bordered table-responsive table-striped table-hover">
            <thead class="table-dark">
                <tr>
                    <th>Description</th>
                    

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Events)
                {
                    <tr>
                        <td>@item.Description</td>
                        

                    </tr>
                }
            </tbody>
        </table>
    }
}

@* @{
    if (@Model.x != null) {
        <h3>Events</h3>
        <table>
        <thead>
        <tr>
        <th>Description</th>
        <th>Meeting room</th>
        <th>Capacity</th>
        </tr>
        </thead>
        <tbody>


        @foreach (var i in @Model.x) {
            <tr>
            <td>@i.Description</td>
            <td>@i.MeetingRoom</td>

            </tr>
        }
        </tbody>

        </table>
    }

} *@

Capstone/Pages/Menu.cshtml
@page
@model MenuModel
@{
    ViewData["Title"] = "Home Page";
  
}

<head>
    <style>
        main {
            padding-top: 3em!important;
        }
    </style>
</head>

<link href="~/css/custom.css" rel="stylesheet" />

<div class="container-fluid">
    <div class="row">
      
        <!-- Main section -->
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <!-- My Upcoming Events Section -->
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">My Upcoming Events</h1>
            </div>
            <div class="row">
                @foreach (var ev in Model.UpcomingEvents)
                {
                    <div class="col-12 col-lg-6 mb-3">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">@ev.Name</h5>
                                <p class="card-text">@ev.Description</p>
                                <p class="card-text">@ev.StartDate - @ev.EndDate</p>
                                <!-- Add more details as needed -->
                            </div>
                        </div>
                    </div>
                }
            </div>

           
        </main>
    </div>
</div>

<script src="~/js/site.js"></script>
<script>
    
</script>

<form asp-page="DBLogin" asp-page-handler="LogoutHandler">
    <input type="submit" class="btn btn-danger" value="logout">
</form>

Capstone/Pages/SignUp.cshtml
@page
@model Capstone.Pages.SignUpModel
@{

}
<head>
    <style>
        nav, .side-nav {
            visibility: hidden!important;
        }
    </style>
</head>
<form method="post">
    <h1>Register Here!</h1>
    <label>First Name:</label>
    <input type="text" asp-for="NewUser.FirstName" required id="FirstName" />
    <br />
    <label>Last Name:</label>
    <input type="text" asp-for="NewUser.LastName" required id="LastName" />
    <br />
    <label>Email:</label>
    <input type="email" asp-for="NewUser.Email" required id="Email" />
    <br />
    <label>Phone Number:</label>
    <input type="text" asp-for="NewUser.PhoneNumber" required id="PhoneNumber" />
    <br />
    <label>Username:</label>
    <input type="text" asp-for="NewUser.Username" required id="Username" />
    <br />
    <label>Password:</label>
    <input type="password" asp-for="Password" required id="Password" />
    <br />
    <button type="submit">Register</button>
    <button type="button" class="btn btn-secondary" onclick="populateForm()">Populate</button>
</form>

<script>
    function populateForm() {
        document.getElementById("FirstName").value = "Test";
        document.getElementById("LastName").value = "Organizer";
        document.getElementById("Email").value = "Test@Gmail.com";
        document.getElementById("PhoneNumber").value = "555-555-5555";
        document.getElementById("Username").value = "TestUser";
        document.getElementById("Password").value = "password";
    }
</script>